### ISSUE TITLE
V0.5.22: Cannot find module 'babel-plugin-transform-async-to-promises

### ISSUE THREAD

**Issue by Thykof** [dusaprotocol/sdk#7]
node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module 'babel-plugin-transform-async-to-promises/helpers'
Require stack:
- /Users/nathanmassa/dev/side-projects/dusa-auto-pool/node_modules/@dusalabs/sdk/dist/sdk.cjs.development.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at a._resolveFilename (/Users/nathanmassa/dev/side-projects/dusa-auto-pool/node_modules/tsx/dist/cjs/index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/nathanmassa/dev/side-projects/dusa-auto-pool/node_modules/@dusalabs/sdk/dist/sdk.cjs.development.js:14:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.S (/Users/nathanmassa/dev/side-projects/dusa-auto-pool/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/nathanmassa/dev/side-projects/dusa-auto-pool/node_modules/@dusalabs/sdk/dist/sdk.cjs.development.js'
  ]
}

**Comment by JoeTheCookie217** [comment]
fixed in 0.5.23

**Comment by Thykof** [comment]
I still have the problem and v0.5.23 only format the code

**Comment by JoeTheCookie217** [comment]
mb
this should work now
